### ISSUE TITLE
Wrong GPU settings

### ISSUE THREAD

**Issue by davordragic** [joostiphone/Hackintosh#2]
You have Graphic card: Sapphire Nitro+ Radeon RX 570 4GD5 in Readme.

But when I look into your config.plist, you're Injecting Intel (under Graphics) and injecting FakeId of Intel GPU in Devices tab.

That does not work properly. Did you remove AMD gpu or you forgot to fix this?

**Comment by davordragic** [comment]
I see it works despite having Intel gpu injected, I have remoted that and still works.

But I have noticed that RX580 (in my case) have poor GeekBench score. only 40k with gpu test

**Comment by joostiphone** [comment]
Yea, I don't have any problems with this. Still injected it due to onboard GPU.

**Comment by davordragic** [comment]
Is there any reason to leave onboard GPU enabled? I have disabled it.
